// packages/core/src/components/organisms/table/table.component.tsx
import {
    Component,
    Element,
    Event,
    EventEmitter,
    h,
    Host,
    Listen,
    Prop,
    State,
    Watch,
} from '@stencil/core';
import { IconVariant } from '../../../components';
import { QuickFilter, RowClickEvent } from '../../../types/table';
import { formatTranslation, getLocaleComponentStrings } from '../../../utils';
import { TableColumn } from '../../helpers/table-column/table-column.component';
import {
    defaultSize,
    defaultSizeOptions,
} from '../../molecules/page-size-select/constants';
import { buttonTemplateFunc } from '../../molecules/table-header/table-header.component';

export type templateFunc = () => string;

@Component({
    tag: 'p-table',
    styleUrl: 'table.component.scss',
})
export class Table {
    /**
     * The items to be fed to the table
     */
    @Prop() items: string;

    /**
     * Wether data is loading
     */
    @Prop() loading: boolean = false;

    /**
     * Wether the header should show loading state
     */
    @Prop() headerLoading: boolean = false;

    /**
     * Wether the footer should show loading state
     */
    @Prop() footerLoading: boolean = false;

    /**
     * The amount of loading rows to show
     */
    @Prop() amountOfLoadingRows: number = 6;

    /**
     * Wether to enable selection
     */
    @Prop() enableRowSelection: boolean = true;

    /**
     * Wether to enable row clicking
     */
    @Prop() enableRowClick: boolean = true;

    /**
     * The current selection of items
     */
    @Prop() selectedRows: any[] = [];

    /**
     * Event whenever the current selection changes
     */
    @Event() selectedRowsChange: EventEmitter<any>;

    /**
     * The key to determine if a row is selected
     */
    @Prop() selectionKey: string;

    /**
     * A key to determine if a row can be selected
     */
    @Prop() canSelectKey: string;

    /**
     * Event whenever a row is clicked
     */
    @Event() rowClick: EventEmitter<RowClickEvent>;

    /**
     * Event whenever a row is selected
     */
    @Event() rowSelected: EventEmitter<any>;

    /**
     * Event whenever a row is deselected
     */
    @Event() rowDeselected: EventEmitter<any>;

    /**
     * Event when the table has rendered
     */
    @Event() hasRendered: EventEmitter<number>;

    /** START HEADER */

    /**
     * Wether to show the header
     */
    @Prop() enableHeader: boolean = true;

    /**
     * Quick filters to show
     */
    @Prop() quickFilters: QuickFilter[] = [];

    /**
     * Active quick filter identifier
     */
    @Prop() activeQuickFilterIdentifier: string;

    /**
     * Wether to show the search input
     */
    @Prop() enableSearch: boolean = true;

    /**
     * The query to show in the search bar
     */
    @Prop({ mutable: true }) query: string;

    /**
     * Wether to show the filter button
     */
    @Prop() enableFilter: boolean = true;

    /**
     * The amount of filters being selected
     */
    @Prop() selectedFiltersAmount: number;

    /**
     * The template for the filter button text
     */
    @Prop() filterButtonTemplate: templateFunc;

    /**
     * Wether to show the edit button
     */
    @Prop() enableEdit: boolean = true;

    /**
     * The edit button icon
     */
    @Prop() editButtonIcon: IconVariant = 'pencil';

    /**
     * The edit button text if changed
     */
    @Prop() editButtonText: string;

    /**
     * The template for the edit button text
     */
    @Prop() editButtonTemplate: buttonTemplateFunc;

    /**
     * Event when one of the quick filters is clicked
     */
    @Event() quickFilter: EventEmitter<QuickFilter>;

    /**
     * Event when the query changes
     */
    @Event() queryChange: EventEmitter<string>;

    /**
     * Event when the filter button is clicked
     */
    @Event() filter: EventEmitter<null>;

    /**
     * Event when the edit button is clicked
     */
    @Event() edit: EventEmitter<null>;

    /** START FOOTER */

    /**
     * Wether to show the header
     */
    @Prop() enableFooter: boolean = true;

    /**
     * Wether to enable page size select
     */
    @Prop() enablePageSize: boolean = true;

    /**
     * Wether to enable pagination
     */
    @Prop() enablePagination: boolean = true;

    /**
     * Wether to enable export
     */
    @Prop() enableExport: boolean = true;

    /**
     * The current page
     */
    @Prop({ mutable: true, reflect: true }) page: number = 1;

    /**
     * The total amount of items
     */
    @Prop() total!: number;

    /**
     * Event whenever the page changes
     */
    @Event() pageChange: EventEmitter<number>;

    /**
     * The amount of items per page
     */
    @Prop() pageSize: number = defaultSize;

    /**
     * The options for the page size
     */
    @Prop() pageSizeOptions: number[] = defaultSizeOptions;

    /**
     * Event whenever the page changes
     */
    @Event() pageSizeChange: EventEmitter<number>;

    /**
     * Event whenever the page changes
     */
    @Event() export: EventEmitter<number>;

    /**
     * Wether to hide when there is only 1 page available
     */
    @Prop() hideOnSinglePage: boolean = true;

    /* Empty state start */
    @Prop() emptyStateHeader: templateFunc = () =>
        formatTranslation(this._locales.empty_state?.no_filter.header);
    @Prop() emptyStateContent: templateFunc = () =>
        formatTranslation(this._locales.empty_state?.no_filter.content);
    @Prop() emptyStateAction: templateFunc = () =>
        formatTranslation(this._locales.empty_state?.no_filter.action);
    /**
     * Wether to enable empty state action
     */
    @Prop() enableEmptyStateAction: boolean = true;

    @Prop() emptyStateFilteredHeader: templateFunc = () =>
        formatTranslation(this._locales.empty_state.filtered.header);
    @Prop() emptyStateFilteredContent: templateFunc = () =>
        formatTranslation(this._locales.empty_state.filtered.content);

    /**
     * Event whenever the empty state is clicked
     */
    @Event() emptyStateActionClick: EventEmitter<null>;

    /* Empty state end */

    /**
     * The host element
     */
    @Element() private _el: HTMLElement;

    /**
     * Locales used for this component
     */
    @State() private _locales: any = {};

    @State() private _columns: any[] = [];
    @State() private _items: any[] = [];

    private _ctrlDown = false;
    private _hasCustomFilterSlot = false;

    componentWillLoad() {
        this._hasCustomFilterSlot = !!this._el.querySelector(
            ':scope > [slot="custom-filter"]'
        );

        this._setLocales();
        this._parseItems(this.items);
        this._generateColumns();
    }

    componentDidRender() {
        this.hasRendered.emit();
    }

    render() {
        return (
            <Host class="p-table">
                <p-table-container>
                    {this.enableHeader && (
                        <p-table-header
                            // quick filters
                            quickFilters={this.quickFilters}
                            activeQuickFilterIdentifier={
                                this.activeQuickFilterIdentifier
                            }
                            onQuickFilter={({ detail }) =>
                                this.quickFilter.emit(detail)
                            }
                            // search
                            enableSearch={this.enableSearch}
                            query={this.query}
                            onQueryChange={({ detail }) =>
                                this.queryChange.emit(detail)
                            }
                            // filter button
                            enableFilter={this.enableFilter}
                            selectedFiltersAmount={this.selectedFiltersAmount}
                            filterButtonTemplate={this.filterButtonTemplate}
                            onFilter={() => this.filter.emit()}
                            // edit button
                            enableEdit={this.enableEdit}
                            editIcon={this.editButtonIcon}
                            editText={this.editButtonText}
                            canEdit={!!this.selectedRows?.length}
                            editButtonTemplate={this.editButtonTemplate}
                            onEdit={() => this.edit.emit()}
                            itemsSelectedAmount={this.selectedRows?.length}
                            //loading
                            loading={this.headerLoading}
                        >
                            {this._hasCustomFilterSlot && (
                                <slot
                                    name="custom-filter"
                                    slot="custom-filter"
                                />
                            )}
                        </p-table-header>
                    )}

                    {this._getHeader()}
                    <div class="flex flex-col">{this._getRows()}</div>

                    {this.enableFooter && (
                        <p-table-footer
                            // overall
                            hideOnSinglePage={this.hideOnSinglePage}
                            // page size select
                            enablePageSize={this.enablePageSize}
                            pageSize={this.pageSize}
                            pageSizeOptions={this.pageSizeOptions}
                            onPageSizeChange={({ detail }) =>
                                this.pageSizeChange.emit(detail)
                            }
                            // pagination
                            enablePagination={this.enablePagination}
                            page={this.page}
                            total={this.total}
                            onPageChange={({ detail }) =>
                                this.pageChange.emit(detail)
                            }
                            // export
                            enableExport={this.enableExport}
                            onExport={() => this.export.emit()}
                            //loading
                            loading={this.footerLoading}
                        ></p-table-footer>
                    )}
                </p-table-container>
            </Host>
        );
    }

    @Listen('localeChanged', { target: 'body' })
    private async _setLocales(): Promise<void> {
        this._locales = await getLocaleComponentStrings(this._el);
    }

    @Listen('tableDefinitionChanged', { target: 'body' })
    onTableDefinitionUpdated() {
        this._generateColumns();
    }

    @Listen('keydown', { target: 'document' })
    keyDown({ key }) {
        if (key !== 'Control' || this._ctrlDown === true) {
            return;
        }

        this._ctrlDown = true;
    }

    @Listen('keyup', { target: 'document' })
    keyUp({ key }) {
        if (key !== 'Control' || this._ctrlDown === false) {
            return;
        }

        this._ctrlDown = false;
    }

    @Listen('visibilitychange', { target: 'document' })
    visibilityChange() {
        if (document.visibilityState !== 'hidden' || this._ctrlDown === false) {
            return;
        }

        this._ctrlDown = false;
    }

    @Watch('items')
    private _parseItems(items: string) {
        if (!items) {
            this._items = [];
            return;
        }

        if (Array.isArray(items)) {
            this._items = items;
            return;
        }

        this._items = JSON.parse(items);
    }

    private _generateColumns() {
        const definitions = this._el.querySelectorAll('p-table-column');
        this._columns = Array.from(definitions);
    }

    private _getHeader() {
        return (
            <p-table-row variant="header">
                {this._columns.map((col: TableColumn, index) => (
                    <p-table-cell
                        definition={col}
                        value={col.name}
                        variant="header"
                        checkbox={this._getCheckbox(index, null, 'header')}
                        index={index}
                    ></p-table-cell>
                ))}
            </p-table-row>
        );
    }

    private _getRows() {
        if (this.loading) {
            return Array.from(
                {
                    length: this.amountOfLoadingRows,
                },
                (_, i) => (
                    <p-table-row
                        enableHover={
                            this.enableRowSelection || this.enableRowClick
                        }
                    >
                        {this._getLoadingColumns(i)}
                    </p-table-row>
                )
            );
        }

        if (!this._items.length) {
            return this._getEmptyState();
        }

        return this._items.map((item, index) => (
            <p-table-row
                enableHover={this.enableRowSelection || this.enableRowClick}
                onClick={(ev) => this._rowClick(ev, index)}
            >
                {this._getRowColumns(item, index)}
            </p-table-row>
        ));
    }

    private _getRowColumns(item, index) {
        return this._columns.map((col: TableColumn, colIndex) => {
            return (
                <p-table-cell
                    definition={col}
                    item={item}
                    checkbox={this._getCheckbox(colIndex, index)}
                    index={colIndex}
                    rowIndex={index}
                ></p-table-cell>
            );
        });
    }

    private _getLoadingColumns(index) {
        return this._columns.map((col: TableColumn, colIndex) => {
            return (
                <p-table-cell
                    definition={col}
                    variant="loading"
                    checkbox={this._getCheckbox(colIndex, index, 'loading')}
                    index={colIndex}
                    rowIndex={index}
                ></p-table-cell>
            );
        });
    }

    private _getCheckbox(
        index,
        rowIndex,
        variant: 'header' | 'default' | 'loading' = 'default'
    ) {
        if (!this.enableRowSelection || !this.selectionKey || index !== 0) {
            return;
        }

        if (variant === 'loading') {
            return <p-loader variant="ghost" class="h-6 w-6 rounded" />;
        }

        if (variant === 'header') {
            return (
                <input
                    class="p-input"
                    type="checkbox"
                    onChange={(ev) => this._selectAllChange(ev)}
                    checked={this._selectionContainsAll()}
                    indeterminate={this._selectionIndeterminate()}
                />
            );
        }

        const item = this._items[rowIndex];

        return (
            <input
                class="p-input"
                type="checkbox"
                onChange={(ev) => this._checkboxChange(ev?.target, rowIndex)}
                disabled={this.canSelectKey && !item[this.canSelectKey]}
                checked={this._selectionContains(item, rowIndex)}
            />
        );
    }

    private _getEmptyState() {
        if (this.query?.length || this.selectedFiltersAmount) {
            return (
                <div class="flex max-w-[20rem] flex-col items-center self-center py-24 text-center">
                    <p-illustration variant="empty-state-search" class="mb-6" />
                    <p class="text-storm-default font-semibold">
                        {this.emptyStateFilteredHeader()}
                    </p>
                    <p class="mb-14 text-sm text-storm-medium">
                        {this.emptyStateFilteredContent()}
                    </p>
                </div>
            );
        }

        return (
            <div class="flex max-w-[20rem] flex-col items-center self-center py-24 text-center">
                <p-illustration
                    variant="empty-state-overview"
                    class="mb-6 cursor-pointer"
                    onClick={() => this.emptyStateActionClick.emit(null)}
                />
                <p class="text-storm-default font-semibold">
                    {this.emptyStateHeader()}
                </p>
                <p class="mb-6 text-sm text-storm-medium">
                    {this.emptyStateContent()}
                </p>
                {this.enableEmptyStateAction && (
                    <p-button
                        variant="secondary"
                        icon="plus"
                        size="small"
                        onClick={() => this.emptyStateActionClick.emit(null)}
                    >
                        {this.emptyStateAction()}
                    </p-button>
                )}
            </div>
        );
    }

    private _selectAllChange($event: any) {
        if (!this.enableRowSelection) {
            return;
        }

        const value = this._getCheckedValue($event.target);
        if (value) {
            const toAdd = [];
            for (let i = 0; i < this._items.length; i++) {
                const row = this._items[i];
                if (this.canSelectKey && !row[this.canSelectKey]) {
                    continue;
                }

                if (this._selectionContains(row, i)) {
                    continue;
                }

                toAdd.push(row);
                this.rowSelected.emit(row);
            }

            this.selectedRows = [...this.selectedRows, ...toAdd];
            this.selectedRowsChange.emit(this.selectedRows);
            return;
        }

        for (let i = 0; i < this.selectedRows.length; i++) {
            const value = this.selectedRows[i];
            const row = this._items.find(
                (d) =>
                    this._getSelectionValue(d, i) ===
                    this._getSelectionValue(value, i)
            );

            if (!row) {
                continue;
            }

            this.rowDeselected.emit(row);
        }

        this.selectedRows = [];
        this.selectedRowsChange.emit(this.selectedRows);
    }

    private _checkboxChange(target: any, index: number) {
        if (!this.enableRowSelection) {
            return;
        }

        const row = this._items[index];

        if (this.canSelectKey && !row[this.canSelectKey]) {
            target.checked = false;
            return;
        }

        const value = this._getCheckedValue(target);
        if (value) {
            this.selectedRows = [...this.selectedRows, row];
            this.selectedRowsChange.emit(this.selectedRows);
            this.rowSelected.emit(row);
            return;
        }

        const indexOfToRemove = this._selectionContains(row, index, true);

        // we need to do this, because splice does not trigger the selection setter.
        const selection = [...this.selectedRows];
        selection.splice(indexOfToRemove, 1);
        this.selectedRows = selection;
        this.selectedRowsChange.emit(this.selectedRows);
        this.rowDeselected.emit(row);
    }

    private _getCheckedValue(target: any) {
        return target?.checked;
    }

    private _getSelectionValue(row: any, index: number) {
        return this.selectionKey ? row?.[this.selectionKey] || index : index;
    }

    private _selectionContains(row, index, returnIndex = false): any {
        const returnValue = this.selectedRows.findIndex(
            (item) =>
                this._getSelectionValue(row, index) ===
                this._getSelectionValue(item, index)
        );
        return !returnIndex ? returnValue >= 0 : returnValue;
    }

    private _selectionContainsAll() {
        let returnValue = true;
        if (!this._items?.length) {
            return false;
        }

        for (let i = 0; i < this._items?.length; i++) {
            const item = this._items[i];
            const contains = this._selectionContains(item, i);

            if (!contains) {
                returnValue = false;
                break;
            }
        }

        return returnValue;
    }

    private _selectionIndeterminate() {
        if (!this._items?.length || !this.selectedRows?.length) {
            return false;
        }

        let containsCount = 0;
        for (let i = 0; i < this._items?.length; i++) {
            const item = this._items[i];
            const contains = this._selectionContains(item, i);

            if (contains) {
                containsCount++;
            }
        }

        return containsCount > 0 && containsCount !== this._items.length;
    }

    private _rowClick($event, index) {
        const target = $event.target;

        if (
            target.tagName.toLowerCase() === 'input' ||
            target.type === 'checkbox'
        ) {
            return;
        }

        const row = this._findRow($event.target);

        if (this.enableRowClick) {
            const action = this._findRowAction($event.target);

            if (action) {
                return;
            }

            const item = this._items[index];
            this.rowClick.emit({
                item,
                ctrlDown: this._ctrlDown,
            });
            return;
        }

        if (!this.enableRowSelection) {
            return;
        }

        const checkbox = row?.querySelector('input[type="checkbox"]');

        if (!checkbox) {
            return;
        }

        checkbox.checked = !checkbox.checked;
        this._checkboxChange(checkbox, index);
    }

    private _findRow(el: HTMLElement) {
        if (!el) {
            return el;
        }

        if (el?.tagName?.toLowerCase() === 'p-table-row') {
            return el;
        }

        return this._findRow(el?.parentElement);
    }

    private _findRowAction(el: HTMLElement) {
        if (!el) {
            return null;
        }

        if (
            el.getAttribute('data-is-action') !== null &&
            el.getAttribute('data-is-action') !== 'false'
        ) {
            return el;
        }

        if (el?.tagName?.toLowerCase() === 'p-table-row') {
            return null;
        }

        return this._findRowAction(el?.parentElement);
    }
}

// packages/angular/projects/paperless/src/lib/modules/table/components/table/table.component.ts
import {
    ChangeDetectionStrategy,
    Component,
    ContentChild,
    ContentChildren,
    EventEmitter,
    HostListener,
    Input,
    OnChanges,
    OnInit,
    Output,
    QueryList,
    SimpleChanges,
    TemplateRef,
} from '@angular/core';
import { UntilDestroy } from '@ngneat/until-destroy';
import { QuickFilter, RowClickEvent } from '@paperless/core';
import { TableFilterModalDirective } from '../../directives/p-table-filter-modal.directive';
import { TableColumn } from '../table-column/table-column.component';
import { defaultSize, defaultSizeOptions } from './constants';

@UntilDestroy({ checkProperties: true })
@Component({
    selector: 'p-table-ngx',
    templateUrl: 'table.component.html',
    styleUrls: ['table.component.scss'],
    changeDetection: ChangeDetectionStrategy.OnPush,
})
export class Table implements OnInit, OnChanges {
    /**
     * The items to be fed to the table
     */
    @Input() items!: string;

    /**
     * Wether data is loading
     */
    @Input() loading: boolean = false;

    /**
     * The amount of loading rows to show
     */
    @Input() amountOfLoadingRows: number = 6;

    /**
     * Wether to enable selection
     */
    @Input() enableRowSelection: boolean = true;

    /**
     * Wether to enable row clicking
     */
    @Input() enableRowClick: boolean = true;

    /**
     * The current selection of items
     */
    @Input() selectedRows: any[] = [];

    /**
     * Event whenever the current selection changes
     */
    @Output() selectedRowsChange: EventEmitter<any> = new EventEmitter();

    /**
     * The key to determine if a row is selected
     */
    @Input() selectionKey: string | undefined;

    /**
     * A key to determine if a row can be selected
     */
    @Input() canSelectKey: string | undefined;

    /**
     * Event whenever a row is clicked
     */
    @Output() rowClick: EventEmitter<RowClickEvent> = new EventEmitter();

    /**
     * Event whenever a row is selected
     */
    @Output() rowSelected: EventEmitter<any> = new EventEmitter();

    /**
     * Event whenever a row is deselected
     */
    @Output() rowDeselected: EventEmitter<any> = new EventEmitter();

    /** START HEADER */
    /**
     * Quick filters to show
     */
    @Input() quickFilters: QuickFilter[] = [];

    /**
     * Active quick filter identifier
     */
    @Input() activeQuickFilterIdentifier: string | undefined;

    /**
     * Wether to show the search input
     */
    @Input() enableSearch: boolean = true;

    /**
     * The query to show in the search bar
     */
    @Input() query: string | undefined;

    /**
     * Wether to show the filter button
     */
    @Input() enableFilter: boolean = true;

    /**
     * The amount of filters being selected
     */
    @Input() selectedFiltersAmount: number | undefined;

    /**
     * The template for the filter button text
     */
    @Input() filterButtonTemplate: any;

    /**
     * Wether to show the edit button
     */
    @Input() enableEdit: boolean = true;

    /**
     * The template for the edit button text
     */
    @Input() editButtonTemplate: any;

    /**
     * Event when one of the quick filters is clicked
     */
    @Output() quickFilter: EventEmitter<QuickFilter> = new EventEmitter();

    /**
     * Event when the query changes
     */
    @Output() queryChange: EventEmitter<string> = new EventEmitter();

    /**
     * Event when the filter button is clicked
     */
    @Output() filter: EventEmitter<null> = new EventEmitter();

    /**
     * Event when the edit button is clicked
     */
    @Output() edit: EventEmitter<null> = new EventEmitter();

    /** START FOOTER */

    /**
     * Wether to enable page size select
     */
    @Input() enablePageSize: boolean = true;

    /**
     * Wether to enable pagination
     */
    @Input() enablePagination: boolean = true;

    /**
     * Wether to enable export
     */
    @Input() enableExport: boolean = true;

    /**
     * The current page
     */
    @Input() page: number = 1;

    /**
     * The total amount of items
     */
    @Input() total!: number;

    /**
     * Event whenever the page changes
     */
    @Output() pageChange: EventEmitter<number> = new EventEmitter();

    /**
     * The amount of items per page
     */
    @Input() pageSize: number = defaultSize;

    /**
     * The options for the page size
     */
    @Input() pageSizeOptions: number[] = defaultSizeOptions;

    /**
     * Event whenever the page changes
     */
    @Output() pageSizeChange: EventEmitter<number> = new EventEmitter();

    /**
     * Event whenever the page changes
     */
    @Output() export: EventEmitter<number> = new EventEmitter();

    /**
     * Wether to hide when there is only 1 page available
     */
    @Input() hideOnSinglePage: boolean = true;

    /* Empty state start */
    @Input() emptyStateType: 'no_filter' | 'filtered' = 'no_filter';

    @Input() emptyStateHeader!: string;
    @Input() emptyStateContent!: string;
    @Input() emptyStateAction!: string;

    @Input() emptyStateFilteredHeader!: string;
    @Input() emptyStateFilteredContent!: string;

    /**
     * Event whenever the empty state is clicked
     */
    @Output() emptyStateActionClick: EventEmitter<null> = new EventEmitter();

    /* Empty state end */

    public columns: any[] = [];
    public parsedItems: any[] = [];
    public loadingRows = Array.from({
        length: this.amountOfLoadingRows,
    });
    private _ctrlDown = false;

    // Angular stuff
    // column templates
    private _columnDefinitions!: QueryList<TableColumn>;

    @ContentChildren(TableColumn)
    set columnDefinitions(v: QueryList<TableColumn>) {
        this._columnDefinitions = v;
        this._generateColumns();
    }
    get columnDefinitions(): QueryList<TableColumn> {
        return this._columnDefinitions;
    }

    // filter modal
    @ContentChild(TableFilterModalDirective, {
        read: TemplateRef,
        static: true,
    })
    public filterModalTemplate: TemplateRef<any> | undefined;
    private _filterModalShow = false;

    set filterModalShow(value: boolean) {
        this._filterModalShow = value;
        this.filterModalShown.next(this._filterModalShow);
    }
    get filterModalShow() {
        return this._filterModalShow;
    }

    @Input() filterModalHeaderText: string = 'Filters';
    @Input() filterModalSaveText: string = 'Save';
    @Input() filterModalCancelText: string = 'Cancel';

    @Output() filterModalShown: EventEmitter<boolean> = new EventEmitter();

    constructor() {}

    ngOnInit() {
        this._parseItems(this.items);

        this.loadingRows = Array.from({
            length: this.amountOfLoadingRows,
        });
        // this._generateColumns();
    }

    ngOnChanges(changes: SimpleChanges) {
        if (changes['items']) {
            this._parseItems(changes['items'].currentValue);
        }

        if (changes['amountOfLoadingRows']) {
            this.loadingRows = Array.from({
                length: changes['amountOfLoadingRows'].currentValue,
            });
        }
    }

    //  @HostListener('body:tableDefinitionChanged', { target: 'body' })
    //  onTableDefinitionUpdated() {
    //      this._generateColumns();
    //  }

    @HostListener('document:keydown', ['$event'])
    keyDown({ key }: { key: string }) {
        if (key !== 'Control' || this._ctrlDown === true) {
            return;
        }

        this._ctrlDown = true;
    }

    @HostListener('document:keyup', ['$event'])
    keyUp({ key }: { key: string }) {
        if (key !== 'Control' || this._ctrlDown === false) {
            return;
        }

        this._ctrlDown = false;
    }

    @HostListener('document:visibilitychange', ['$event'])
    visibilityChange() {
        if (document.visibilityState !== 'hidden' || this._ctrlDown === false) {
            return;
        }

        this._ctrlDown = false;
    }

    onQueryChange({ detail }: CustomEvent<string>) {
        this.queryChange.emit(detail);
    }

    onQuickFilter({ detail }: CustomEvent<any>) {
        this.quickFilter.emit(detail);
    }

    onPageSizeChange({ detail }: CustomEvent<number>) {
        this.pageSizeChange.emit(detail);
    }

    onPageChange({ detail }: CustomEvent<number>) {
        this.pageChange.emit(detail);
    }

    filterModalSave() {
        this.filter.emit();
        this.filterModalShow = false;
    }

    private _parseItems(items: string) {
        if (!items) {
            this.parsedItems = [];
            return;
        }

        if (Array.isArray(items)) {
            this.parsedItems = items;
            return;
        }

        this.parsedItems = JSON.parse(items);
    }

    private _generateColumns() {
        // const definitions =
        // 	this._el.nativeElement.querySelectorAll('p-table-definition');
        this.columns = Array.from(this._columnDefinitions);
    }

    //  private _getHeader() {
    //      return (
    //          <p-table-row variant="header">
    //              {this._columns.map((col: TableDefinition, index) => (
    //                  <p-table-column
    //                      definition={col}
    //                      value={col.name}
    //                      variant="header"
    //                      checkbox={this._getCheckbox(index, null, 'header')}
    //                      index={index}
    //                  ></p-table-column>
    //              ))}
    //          </p-table-row>
    //      );
    //  }

    //  private _getRows() {
    //      if (this.loading) {
    //          return Array.from(
    //              {
    //                  length: this.amountOfLoadingRows,
    //              },
    //              (_, i) => (
    //                  <p-table-row
    //                      enableHover={
    //                          this.enableRowSelection || this.enableRowClick
    //                      }
    //                  >
    //                      {this._getLoadingColumns(i)}
    //                  </p-table-row>
    //              )
    //          );
    //      }

    //      return this._items.map((item, index) => (
    //          <p-table-row
    //              enableHover={this.enableRowSelection || this.enableRowClick}
    //              onClick={(ev) => this._rowClick(ev, index)}
    //          >
    //              {this._getRowColumns(item, index)}
    //          </p-table-row>
    //      ));
    //  }

    //  private _getRowColumns(item, index) {
    //      return this._columns.map((col: TableDefinition, colIndex) => {
    //          return (
    //              <p-table-column
    //                  definition={col}
    //                  item={item}
    //                  checkbox={this._getCheckbox(colIndex, index)}
    //                  index={colIndex}
    //                  rowIndex={index}
    //              ></p-table-column>
    //          );
    //      });
    //  }

    //  private _getLoadingColumns(index) {
    //      return this._columns.map((col: TableDefinition, colIndex) => {
    //          return (
    //              <p-table-column
    //                  definition={col}
    //                  variant="loading"
    //                  checkbox={this._getCheckbox(colIndex, index, 'loading')}
    //                  index={colIndex}
    //                  rowIndex={index}
    //              ></p-table-column>
    //          );
    //      });
    //  }

    //  private _getCheckbox(
    //      index,
    //      rowIndex,
    //      variant: 'header' | 'default' | 'loading' = 'default'
    //  ) {
    //      if (!this.enableRowSelection || !this.selectionKey || index !== 0) {
    //          return;
    //      }

    //      if (variant === 'loading') {
    //          return <p-loader variant="ghost" class="rounded w-6 h-6" />;
    //      }

    //      if (variant === 'header') {
    //          return (
    //              <input
    //                  class="p-input"
    //                  type="checkbox"
    //                  onChange={(ev) => this._selectAllChange(ev)}
    //                  checked={this._selectionContainsAll()}
    //                  indeterminate={this._selectionIndeterminate()}
    //              />
    //          );
    //      }

    //      const item = this._items[rowIndex];

    //      return (
    //          <input
    //              class="p-input"
    //              type="checkbox"
    //              onChange={(ev) => this._checkboxChange(ev?.target, rowIndex)}
    //              disabled={this.canSelectKey && !item[this.canSelectKey]}
    //              checked={this._selectionContains(item, rowIndex)}
    //          />
    //      );
    //  }

    public _checkboxDisabled(item: any) {
        return this.canSelectKey && !item[this.canSelectKey];
    }

    public _selectAllChange($event: any) {
        if (!this.enableRowSelection) {
            return;
        }

        const value = this._getCheckedValue($event.target);
        if (value) {
            const toAdd = [];
            for (let i = 0; i < this.parsedItems.length; i++) {
                const row = this.parsedItems[i];
                if (this.canSelectKey && !row[this.canSelectKey]) {
                    continue;
                }

                if (this._selectionContains(row, i)) {
                    continue;
                }

                toAdd.push(row);
                this.rowSelected.emit(row);
            }

            this.selectedRows = [...this.selectedRows, ...toAdd];
            this.selectedRowsChange.emit(this.selectedRows);
            return;
        }

        for (let i = 0; i < this.selectedRows.length; i++) {
            const value = this.selectedRows[i];
            const row = this.parsedItems.find(
                (d) =>
                    this._getSelectionValue(d, i) ===
                    this._getSelectionValue(value, i)
            );

            if (!row) {
                continue;
            }

            this.rowDeselected.emit(row);
        }

        this.selectedRows = [];
        this.selectedRowsChange.emit(this.selectedRows);
    }

    public _checkboxChange(target: any, index: number) {
        if (!this.enableRowSelection) {
            return;
        }

        const row = this.parsedItems[index];

        if (this.canSelectKey && !row[this.canSelectKey]) {
            target.checked = false;
            return;
        }

        const value = this._getCheckedValue(target);
        if (value) {
            this.selectedRows = [...this.selectedRows, row];
            this.selectedRowsChange.emit(this.selectedRows);
            this.rowSelected.emit(row);
            return;
        }

        const indexOfToRemove = this._selectionContains(row, index, true);

        // we need to do this, because splice does not trigger the selection setter.
        const selection = [...this.selectedRows];
        selection.splice(indexOfToRemove, 1);
        this.selectedRows = selection;
        this.selectedRowsChange.emit(this.selectedRows);
        this.rowDeselected.emit(row);
    }

    private _getCheckedValue(target: any) {
        return target?.checked;
    }

    private _getSelectionValue(row: any, index: number) {
        return this.selectionKey ? row?.[this.selectionKey] || index : index;
    }

    public _selectionContains(
        row: any,
        index: number,
        returnIndex = false
    ): any {
        const returnValue = this.selectedRows.findIndex(
            (item) =>
                this._getSelectionValue(row, index) ===
                this._getSelectionValue(item, index)
        );
        return !returnIndex ? returnValue >= 0 : returnValue;
    }

    public _selectionContainsAll() {
        let returnValue = true;
        if (!this.parsedItems?.length) {
            return false;
        }

        for (let i = 0; i < this.parsedItems?.length; i++) {
            const item = this.parsedItems[i];
            const contains = this._selectionContains(item, i);

            if (!contains) {
                returnValue = false;
                break;
            }
        }

        return returnValue;
    }

    public _selectionIndeterminate() {
        if (!this.parsedItems?.length || !this.selectedRows?.length) {
            return false;
        }

        let containsCount = 0;
        for (let i = 0; i < this.parsedItems?.length; i++) {
            const item = this.parsedItems[i];
            const contains = this._selectionContains(item, i);

            if (contains) {
                containsCount++;
            }
        }

        return containsCount > 0 && containsCount !== this.parsedItems.length;
    }

    public _rowClick($event: { target: any }, index: number) {
        const target = $event.target;

        if (
            target.tagName.toLowerCase() === 'input' ||
            target.type === 'checkbox'
        ) {
            return;
        }

        const row = this._findRow($event.target);

        if (this.enableRowClick) {
            const action = this._findRowAction($event.target);

            if (action) {
                return;
            }

            const item = this.parsedItems[index];
            this.rowClick.emit({
                item,
                ctrlDown: this._ctrlDown,
            });
            return;
        }

        if (!this.enableRowSelection) {
            return;
        }

        const checkbox = row?.querySelector('input[type="checkbox"]');

        if (!checkbox) {
            return;
        }

        checkbox.checked = !checkbox.checked;
        this._checkboxChange(checkbox, index);
    }

    private _findRow(el: HTMLElement | null): any {
        if (!el) {
            return el;
        }

        if (el?.tagName?.toLowerCase() === 'p-table-row') {
            return el;
        }

        return this._findRow(el?.parentElement);
    }

    private _findRowAction(el: HTMLElement | null): any {
        if (!el) {
            return null;
        }

        if (
            el.getAttribute('data-is-action') !== null &&
            el.getAttribute('data-is-action') !== 'false'
        ) {
            return el;
        }

        if (el?.tagName?.toLowerCase() === 'p-table-row') {
            return null;
        }

        return this._findRowAction(el?.parentElement);
    }
}

<p-table-container>
    <p-table-header
        *ngIf="enableHeader"
        [quickFilters]="quickFilters"
        [activeQuickFilterIdentifier]="activeQuickFilterIdentifier"
        (quickFilter)="onQuickFilter($event)"
        [enableSearch]="enableSearch"
        [query]="query"
        (queryChange)="onQueryChange($event)"
        [enableFilter]="enableFilter"
        [selectedFiltersAmount]="selectedFiltersAmount"
        [filterButtonTemplate]="filterButtonTemplate"
        (filter)="filterModalShow$.next(true)"
        [enableAction]="enableAction"
        [canUseAction]="actionButtonEnabled"
        [actionButtonTemplate]="actionButtonTemplate"
        [actionLoading]="actionButtonLoading"
        [actionText]="actionButtonText"
        [actionIcon]="actionButtonIcon"
        (action)="action.emit()"
        [itemsSelectedAmount]="selectedRows.length"
        [loading]="headerLoading"
    >
        <ng-container *ngIf="headerCustomFilterTemplate">
            <ng-container
                *ngTemplateOutlet="headerCustomFilterTemplate"
            ></ng-container>
        </ng-container>
    </p-table-header>

    <p-table-row variant="header">
        <ng-container *ngFor="let col of columns; let index = index">
            <p-table-cell-ngx
                [definition]="col"
                [value]="col.name"
                variant="header"
                [index]="index"
                [checkbox]="
                    (index === 0 || col.hasCheckbox) && enableRowSelection
                        ? checkboxTemplate
                        : undefined
                "
            ></p-table-cell-ngx>
            <ng-template #checkboxTemplate>
                <input
                    class="p-input"
                    type="checkbox"
                    (change)="_selectAllChange($event)"
                    [checked]="_selectionContainsAll()"
                    [indeterminate]="_selectionIndeterminate()"
                />
            </ng-template>
        </ng-container>
    </p-table-row>

    <div class="flex flex-col">
        <ng-container *ngIf="loading; else contentTemplate">
            <p-table-row
                *ngFor="let r of loadingRows; let rowIndex = index"
                [enableHover]="enableRowSelection || enableRowClick"
            >
                <ng-container *ngFor="let col of columns; let index = index">
                    <p-table-cell-ngx
                        [definition]="col"
                        variant="loading"
                        [checkbox]="
                            (index === 0 || col.hasCheckbox) &&
                            enableRowSelection
                                ? checkboxTemplate
                                : undefined
                        "
                        [index]="index"
                        [rowIndex]="rowIndex"
                    ></p-table-cell-ngx>
                    <ng-template #checkboxTemplate>
                        <p-loader
                            variant="ghost"
                            class="h-6 w-6 rounded"
                        ></p-loader>
                    </ng-template>
                </ng-container>
            </p-table-row>
        </ng-container>

        <ng-template #contentTemplate>
            <ng-container *ngIf="items?.length; else emptyStateTemplate">
                <p-table-row
                    *ngFor="let item of items; let rowIndex = index"
                    [enableHover]="enableRowSelection || enableRowClick"
                    (click)="_rowClick($event, rowIndex)"
                >
                    <ng-container
                        *ngFor="let col of columns; let index = index"
                    >
                        <p-table-cell-ngx
                            [definition]="col"
                            [item]="item"
                            [checkbox]="
                                (index === 0 || col.hasCheckbox) &&
                                enableRowSelection
                                    ? checkboxTemplate
                                    : undefined
                            "
                            [index]="index"
                            [rowIndex]="rowIndex"
                            [template]="col.template"
                        ></p-table-cell-ngx>

                        <ng-template #checkboxTemplate>
                            <input
                                class="p-input"
                                type="checkbox"
                                (change)="
                                    _checkboxChange($event.target, rowIndex)
                                "
                                [disabled]="_checkboxDisabled(item)"
                                [checked]="_selectionContains(item, rowIndex)"
                            />
                        </ng-template>
                    </ng-container>
                </p-table-row>
            </ng-container>
        </ng-template>
    </div>

    <p-table-footer
        *ngIf="enableFooter"
        [hideOnSinglePage]="hideOnSinglePage"
        [enablePageSize]="enablePageSize"
        [pageSize]="pageSize"
        [pageSizeOptions]="pageSizeOptions"
        (pageSizeChange)="onPageSizeChange($event)"
        [enablePagination]="enablePagination"
        [page]="page"
        [total]="total"
        (pageChange)="onPageChange($event)"
        [enableExport]="enableExport"
        (export)="export.emit()"
        [loading]="footerLoading"
    ></p-table-footer>

    <ng-container *ngIf="enableFloatingMenu && enableRowSelection">
        <p-floating-menu-container
            [class.inactive]="!selectedRows.length"
            [class.shown]="floatingMenuShown$ | async"
        >
            <p-floating-menu-item
                hover="{false}"
                [class]="{
                    hidden: !!floatingMenuContentTemplate,
                    'tablet:flex': !!floatingMenuContentTemplate
                }"
            >
                {{ floatingMenuAmountSelectedText }}
            </p-floating-menu-item>
            <p-divider
                class="mx-0 text-storm"
                variant="vertical"
                [class]="{
                    hidden: !!floatingMenuContentTemplate,
                    'tablet:flex': !!floatingMenuContentTemplate
                }"
            ></p-divider>
            <ng-container *ngIf="floatingMenuContentTemplate">
                <ng-container
                    *ngTemplateOutlet="floatingMenuContentTemplate"
                ></ng-container>
                <p-divider
                    class="mx-0 text-storm"
                    variant="vertical"
                ></p-divider>
            </ng-container>
            <p-floating-menu-item (click)="_selectAllChange(null, false)">
                <p-icon variant="negative"></p-icon>
            </p-floating-menu-item>
        </p-floating-menu-container>
    </ng-container>
</p-table-container>

<ng-container *ngIf="filterModalTemplate">
    <p-modal
        [header]="filterModalHeaderText"
        [show]="filterModalShow$ | async"
        (closed)="filterModalShow$.next(false)"
    >
        <div slot="content" class="flex flex-col gap-6">
            <ng-container
                *ngTemplateOutlet="filterModalTemplate"
            ></ng-container>
        </div>
        <div slot="footer" class="flex w-full justify-between gap-4">
            <p-button
                *ngIf="filterModalShowResetMobile"
                class="flex w-full tablet:w-auto desktop-xs:hidden"
                variant="secondary"
                (onClick)="onFilterModalReset(true)"
            >
                {{ filterModalResetText }}
            </p-button>
            <p-button
                *ngIf="filterModalShowReset"
                class="hidden w-full tablet:w-auto desktop-xs:flex"
                variant="secondary"
                (onClick)="onFilterModalReset()"
            >
                {{ filterModalResetText }}
            </p-button>
            <p-button
                class="ml-auto w-full tablet:w-auto"
                icon="checkmark"
                (onClick)="onFilterModalSave()"
            >
                {{ filterModalSaveText }}
            </p-button>
        </div>
    </p-modal>
</ng-container>

<ng-template #emptyStateTemplate>
    <div
        *ngIf="emptyStateType === 'filtered'; else emptyStateNonFilterTemplate"
        class="
            flex
            max-w-[20rem]
            flex-col
            items-center
            self-center
            py-24
            text-center
        "
    >
        <p-illustration
            [variant]="emptyStateFilteredIllustration"
            class="mb-6"
        ></p-illustration>
        <p class="text-storm-default font-semibold">
            {{ emptyStateFilteredHeader }}
        </p>
        <p class="mb-14 text-sm text-storm-medium">
            {{ emptyStateFilteredContent }}
        </p>
    </div>
</ng-template>

<ng-template #emptyStateNonFilterTemplate>
    <div
        class="
            flex
            max-w-[20rem]
            flex-col
            items-center
            self-center
            py-24
            text-center
        "
        [class.cursor-pointer]="enableEmptyStateAction"
        (click)="emptyStateClicked()"
    >
        <p-illustration
            [variant]="emptyStateIllustration"
            class="mb-6"
        ></p-illustration>
        <p class="text-storm-default font-semibold">
            {{ emptyStateHeader }}
        </p>
        <p class="mb-6 text-sm text-storm-medium">
            {{ emptyStateContent }}
        </p>
        <p-button
            *ngIf="enableEmptyStateAction"
            variant="secondary"
            icon="plus"
            size="small"
        >
            {{ emptyStateAction }}
        </p-button>
    </div>
</ng-template>
