// packages/angular/projects/paperless/src/lib/modules/table/components/table-cell/table-cell.component.ts
/* eslint-disable max-len */
import { Component, HostBinding, Input, TemplateRef } from '@angular/core';
import {
	isTableColumnSizesKey,
	objectGetByPath,
	TableColumnSizes,
	TableColumnSizesKey,
	TableDefinitionData,
} from '@paperless/core';

@Component({
	selector: 'p-table-cell-ngx',
	styleUrls: ['table-cell.component.scss'],
	templateUrl: './table-cell.component.html',
})
export class TableCell {
	/**
	 * The variant of the column
	 */
	@Input() variant: 'default' | 'loading' | 'header' | 'actions' = 'default';

	/**
	 * The index of the column
	 */
	@Input() index: number = 0;

	/**
	 * The index of the row
	 */
	@Input() rowIndex: number = 0;

	/**
	 * The definition of the table column
	 */
	@Input() definition?: any; // TableDefinition

	/**
	 * The item in question
	 */
	@Input() item: any;

	/**
	 * The value of the column
	 */
	@Input() value: any;

	/**
	 * Wether the table has actions
	 */
	@Input() tableHasActions: boolean = false;

	/**
	 * The checkbox templateRef
	 */
	@Input() checkbox: TemplateRef<any> | undefined;

	/**
	 * The template ref for the content
	 */
	@Input() template: TemplateRef<any> | undefined;

	@HostBinding('class')
	get class() {
		return this.getColumnClasses();
	}

	get data(): TableDefinitionData | { value: string } {
		if (this.variant === 'header') {
			return {
				value: this.value,
			};
		}

		if (this.variant === 'actions') {
			return {
				value: this.value,
				item: this.item,
				index: this.index,
				rowIndex: this.rowIndex,
			};
		}

		return {
			value: this.value ?? objectGetByPath(this.item, this.definition.path),
			item: this.item,
			index: this.index,
			rowIndex: this.rowIndex,
		};
	}

	// render() {
	// 	return (
	// 		<Host
	// 			class={{
	// 				'p-table-column': true,
	// 				[`variant-${this.variant}`]: true,
	// 				...this._getColumnClasses(),
	// 			}}
	// 		>
	// 			{this.checkbox}

	// 			{this.variant === 'loading' ? (
	// 				<p-loader
	// 					variant="ghost"
	// 					class="rounded flex-1 w-full h-6"
	// 				/>
	// 			) : (
	// 				<div class="flex">
	// 					{this.variant === 'header' ? (
	// 						this.data.value
	// 					) : this.definition.useSlot ? (
	// 						<slot />
	// 					) : (
	// 						this.template(this.data as TableDefinitionData)
	// 					)}
	// 				</div>
	// 			)}
	// 		</Host>
	// 	);
	// }

	public getColumnClasses() {
		const sizes = this.definition ? this._getSizes(this.definition) : {};
		const isLastValues = this.definition
			? this._getIsLastValues(this.definition)
			: {};

		return {
			'justify-start':
				!this.definition?.align || this.definition?.align === 'start',
			'justify-center': this.definition?.align === 'center',
			'justify-end': this.definition?.align === 'end',
			'font-semibold':
				this.variant !== 'header' && this.definition?.type === 'th',
			'text-storm-dark':
				this.variant !== 'header' && this.definition?.type === 'th',
			'group-hover:flex': this.variant === 'actions' && this.tableHasActions,
			hidden: this.variant === 'actions' && this.tableHasActions,
			...sizes,
			...isLastValues,
		};
	}

	/*
     With this, we shall hack the system in ways no one would ever have thought.

     w-1/12 w-2/12 w-3/12 w-4/12 w-5/12 w-6/12 w-7/12 w-8/12 w-9/12 w-10/12 w-11/12 w-12/12
     tablet:w-1/12 tablet:w-2/12 tablet:w-3/12 tablet:w-4/12 tablet:w-5/12 tablet:w-6/12 tablet:w-7/12 tablet:w-8/12 tablet:w-9/12 tablet:w-10/12 tablet:w-11/12 tablet:w-12/12
     desktop-xs:w-1/12 desktop-xs:w-2/12 desktop-xs:w-3/12 desktop-xs:w-4/12 desktop-xs:w-5/12 desktop-xs:w-6/12 desktop-xs:w-7/12 desktop-xs:w-8/12 desktop-xs:w-9/12 desktop-xs:w-10/12 desktop-xs:w-11/12 desktop-xs:w-12/12
     desktop-xs:w-1/12 desktop-xs:w-2/12 desktop-xs:w-3/12 desktop-xs:w-4/12 desktop-xs:w-5/12 desktop-xs:w-6/12 desktop-xs:w-7/12 desktop-xs:w-8/12 desktop-xs:w-9/12 desktop-xs:w-10/12 desktop-xs:w-11/12 desktop-xs:w-12/12
     desktop-sm:w-1/12 desktop-sm:w-2/12 desktop-sm:w-3/12 desktop-sm:w-4/12 desktop-sm:w-5/12 desktop-sm:w-6/12 desktop-sm:w-7/12 desktop-sm:w-8/12 desktop-sm:w-9/12 desktop-sm:w-10/12 desktop-sm:w-11/12 desktop-sm:w-12/12
     desktop:w-1/12 desktop:w-2/12 desktop:w-3/12 desktop:w-4/12 desktop:w-5/12 desktop:w-6/12 desktop:w-7/12 desktop:w-8/12 desktop:w-9/12 desktop:w-10/12 desktop:w-11/12 desktop:w-12/12
     desktop-lg:w-1/12 desktop-lg:w-2/12 desktop-lg:w-3/12 desktop-lg:w-4/12 desktop-lg:w-5/12 desktop-lg:w-6/12 desktop-lg:w-7/12 desktop-lg:w-8/12 desktop-lg:w-9/12 desktop-lg:w-10/12 desktop-lg:w-11/12 desktop-lg:w-12/12
     desktop-xl:w-1/12 desktop-xl:w-2/12 desktop-xl:w-3/12 desktop-xl:w-4/12 desktop-xl:w-5/12 desktop-xl:w-6/12 desktop-xl:w-7/12 desktop-xl:w-8/12 desktop-xl:w-9/12 desktop-xl:w-10/12 desktop-xl:w-11/12 desktop-xl:w-12/12
     hidden flex group-hover:hidden group-hover:flex
     tablet:hidden tablet:flex tablet:group-hover:hidden tablet:group-hover:flex
     desktop-xs:hidden desktop-xs:flex desktop-xs:group-hover:hidden desktop-xs:group-hover:flex
     desktop-sm:hidden desktop-sm:flex  desktop-sm:group-hover:hidden desktop-sm:group-hover:flex
     desktop:hidden desktop:flex desktop:group-hover:hidden desktop:group-hover:flex
     desktop-lg:hidden desktop-lg:flex desktop-lg:group-hover:hidden desktop-lg:group-hover:flex
     desktop-xl:hidden desktop-xl:flex desktop-xl:group-hover:hidden desktop-xl:group-hover:flex


        ⠀⠀⠀⠀⠀⣠⣴⣶⣿⣿⠿⣷⣶⣤⣄⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣠⣴⣶⣷⠿⣿⣿⣶⣦⣀⠀⠀⠀⠀⠀
        ⠀⠀⠀⢀⣾⣿⣿⣿⣿⣿⣿⣿⣶⣦⣬⡉⠒⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠚⢉⣥⣴⣾⣿⣿⣿⣿⣿⣿⣿⣧⠀⠀⠀⠀
        ⠀⠀⠀⡾⠿⠛⠛⠛⠛⠿⢿⣿⣿⣿⣿⣿⣷⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣠⣾⣿⣿⣿⣿⣿⠿⠿⠛⠛⠛⠛⠿⢧⠀⠀⠀
        ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⠻⣿⣿⣿⣿⣿⡄⠀⠀⠀⠀⠀⠀⣠⣿⣿⣿⣿⡿⠟⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
        ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⢿⣿⡄⠀⠀⠀⠀⠀⠀⠀⠀⢰⣿⡿⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
        ⠀⠀⠀⠀⠀⠀⠀⣠⣤⠶⠶⠶⠰⠦⣤⣀⠀⠙⣷⠀⠀⠀⠀⠀⠀⠀⢠⡿⠋⢀⣀⣤⢴⠆⠲⠶⠶⣤⣄⠀⠀⠀⠀⠀⠀⠀
        ⠀⠘⣆⠀⠀⢠⣾⣫⣶⣾⣿⣿⣿⣿⣷⣯⣿⣦⠈⠃⡇⠀⠀⠀⠀⢸⠘⢁⣶⣿⣵⣾⣿⣿⣿⣿⣷⣦⣝⣷⡄⠀⠀⡰⠂⠀
        ⠀⠀⣨⣷⣶⣿⣧⣛⣛⠿⠿⣿⢿⣿⣿⣛⣿⡿⠀⠀⡇⠀⠀⠀⠀⢸⠀⠈⢿⣟⣛⠿⢿⡿⢿⢿⢿⣛⣫⣼⡿⣶⣾⣅⡀⠀
        ⢀⡼⠋⠁⠀⠀⠈⠉⠛⠛⠻⠟⠸⠛⠋⠉⠁⠀⠀⢸⡇⠀⠀⠄⠀⢸⡄⠀⠀⠈⠉⠙⠛⠃⠻⠛⠛⠛⠉⠁⠀⠀⠈⠙⢧⡀
        ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣿⡇⢠⠀⠀⠀⢸⣷⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
        ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣾⣿⡇⠀⠀⠀⠀⢸⣿⣷⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣰⠟⠁⣿⠇⠀⠀⠀⠀⢸⡇⠙⢿⣆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
        ⠀⠰⣄⠀⠀⠀⠀⠀⠀⠀⠀⢀⣠⣾⠖⡾⠁⠀⠀⣿⠀⠀⠀⠀⠀⠘⣿⠀⠀⠙⡇⢸⣷⣄⡀⠀⠀⠀⠀⠀⠀⠀⠀⣰⠄⠀
        ⠀⠀⢻⣷⡦⣤⣤⣤⡴⠶⠿⠛⠉⠁⠀⢳⠀⢠⡀⢿⣀⠀⠀⠀⠀⣠⡟⢀⣀⢠⠇⠀⠈⠙⠛⠷⠶⢦⣤⣤⣤⢴⣾⡏⠀⠀
        ⠀⠀⠈⣿⣧⠙⣿⣷⣄⠀⠀⠀⠀⠀⠀⠀⠀⠘⠛⢊⣙⠛⠒⠒⢛⣋⡚⠛⠉⠀⠀⠀⠀⠀⠀⠀⠀⣠⣿⡿⠁⣾⡿⠀⠀⠀
        ⠀⠀⠀⠘⣿⣇⠈⢿⣿⣦⠀⠀⠀⠀⠀⠀⠀⠀⣰⣿⣿⣿⡿⢿⣿⣿⣿⣆⠀⠀⠀⠀⠀⠀⠀⢀⣼⣿⡟⠁⣼⡿⠁⠀⠀⠀
        ⠀⠀⠀⠀⠘⣿⣦⠀⠻⣿⣷⣦⣤⣤⣶⣶⣶⣿⣿⣿⣿⠏⠀⠀⠻⣿⣿⣿⣿⣶⣶⣶⣦⣤⣴⣿⣿⠏⢀⣼⡿⠁⠀⠀⠀⠀
        ⠀⠀⠀⠀⠀⠘⢿⣷⣄⠙⠻⠿⠿⠿⠿⠿⢿⣿⣿⣿⣁⣀⣀⣀⣀⣙⣿⣿⣿⠿⠿⠿⠿⠿⠿⠟⠁⣠⣿⡿⠁⠀⠀⠀⠀⠀
        ⠀⠀⠀⠀⠀⠀⠈⠻⣯⠙⢦⣀⠀⠀⠀⠀⠀⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠀⠀⠀⠀⠀⣠⠴⢋⣾⠟⠀⠀⠀⠀⠀⠀⠀
        ⠀⠀⠀⠀⠀⠀⠀⠀⠙⢧⡀⠈⠉⠒⠀⠀⠀⠀⠀⠀⣀⠀⠀⠀⠀⢀⠀⠀⠀⠀⠀⠐⠒⠉⠁⢀⡾⠃⠀⠀⠀⠀⠀⠀⠀⠀
        ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠳⣄⠀⠀⠀⠀⠀⠀⠀⠀⠻⣿⣿⣿⣿⠋⠀⠀⠀⠀⠀⠀⠀⠀⣠⠟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
        ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⢦⡀⠀⠀⠀⠀⠀⠀⠀⣸⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⢀⡴⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
        ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
        ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠐⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
        ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⣿⡿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
        ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢻⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
        ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠸⣿⣿⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
    */
	private _getSizes(
		{
			sizes,
		}: {
			sizes: 'auto' | 'hidden' | 'full' | number | TableColumnSizes;
		} /* Table Definition */
	) {
		if (sizes === 'auto' || !sizes) {
			return {
				'w-auto': true,
			};
		}

		if (sizes === 'hidden') {
			return {
				hidden: true,
			};
		}

		if (typeof sizes === 'object') {
			sizes = sizes as TableColumnSizes;
			const classes: any = {};
			let previousSize: TableColumnSizesKey | undefined;

			for (let size in sizes) {
				if (!isTableColumnSizesKey(sizes, size)) {
					continue;
				}

				if (size === 'default') {
					if (sizes.default === 'hidden') {
						classes['hidden'] = true;
						previousSize = size;
						continue;
					}

					classes[`w-${sizes.default}/12`] = true;
					previousSize = size;
					continue;
				}

				const currentValue = sizes[size];
				const previousValue = previousSize ? sizes[previousSize] : null;
				if (
					currentValue !== 'hidden' &&
					previousValue &&
					previousValue === 'hidden' &&
					this.variant !== 'actions'
				) {
					classes[`${size}:flex`] = true;
				}

				if (currentValue === 'hidden' && this.variant !== 'actions') {
					classes[`${size}:hidden`] = true;
					previousSize = size;
					continue;
				}

				if (currentValue === 12 || currentValue === 'full') {
					classes[`${size}:w-full`] = true;
				}

				classes[`${size}:w-${currentValue}/12`] = true;
				previousSize = size;
			}

			return classes;
		}

		if (sizes === 12 || sizes === 'full') {
			return {
				'w-full': true,
			};
		}

		// is a number.
		return {
			[`w-${sizes}/12`]: true,
		};
	}

	private _getIsLastValues(
		{
			isLast,
			parsedSizes,
		}: {
			isLast: { [key: string]: boolean };
			parsedSizes: TableColumnSizes;
		} /* Table Definition */
	) {
		const values: { [key: string]: boolean } = {};

		for (let size of Object.keys(isLast)) {
			let prefix = '';
			if (size !== 'default') {
				prefix = `${size}:`;
			}

			values[`${prefix}pr-4`] = !isLast[size];

			values[`${prefix}group-hover:hidden`] =
				isLast[size] && this.tableHasActions && this.variant !== 'actions';

			values[`${prefix}group-hover:flex`] =
				parsedSizes[size as keyof TableColumnSizes] !== 'hidden' ||
				this.variant === 'actions';

			values[`${prefix}flex`] =
				parsedSizes[size as keyof TableColumnSizes] !== 'hidden' &&
				this.variant !== 'actions';
		}

		return values;
	}
}

<ng-container *ngIf="checkbox">
	<ng-container *ngTemplateOutlet="checkbox"></ng-container>
</ng-container>

<ng-container [ngSwitch]="variant">
	<p-loader
		*ngSwitchCase="'loading'"
		variant="ghost"
		class="h-6 w-full flex-1 rounded"
	></p-loader>

	<ng-container *ngSwitchCase="'actions'">
		<ng-container *ngIf="template">
			<ng-container *ngTemplateOutlet="template; context: data"></ng-container>
		</ng-container>
	</ng-container>

	<div
		*ngSwitchCase="'header'"
		class="flex w-full overflow-hidden"
		[class.justify-start]="definition.align === 'start'"
		[class.justify-center]="definition.align === 'center'"
		[class.justify-end]="definition.align === 'end'"
	>
		<ng-container *ngTemplateOutlet="valueTemplate"></ng-container>
	</div>

	<div
		*ngSwitchCase="'default'"
		class="flex min-w-0 flex-1"
		[class.justify-start]="definition.align === 'start'"
		[class.justify-center]="definition.align === 'center'"
		[class.justify-end]="definition.align === 'end'"
	>
		<ng-container *ngIf="template; else valueTemplate">
			<ng-container *ngTemplateOutlet="template; context: data"></ng-container>
		</ng-container>
	</div>
</ng-container>

<ng-template #valueTemplate>
	{{ data.value }}
</ng-template>

// packages/core/src/components/molecules/table-cell/table-cell.component.tsx
import { Component, h, Host, Prop } from '@stencil/core';
import {
	isTableColumnSizesKey,
	TableColumnSizes,
	TableColumnSizesKey,
	TableDefinitionData,
	TableDefinitionTemplateFunc,
} from '../../../types';
import { objectGetByPath } from '../../../utils';
import { TableColumn } from '../../helpers/table-column/table-column.component';

@Component({
	tag: 'p-table-cell',
	styleUrl: 'table-cell.component.scss',
})
export class TableCell {
	/**
	 * The variant of the column
	 */
	@Prop() variant: 'default' | 'loading' | 'header' | 'actions' = 'default';

	/**
	 * The index of the column
	 */
	@Prop() index: number;

	/**
	 * The index of the row
	 */
	@Prop() rowIndex: number;

	/**
	 * The definition of the table column
	 */
	@Prop() definition?: TableColumn;

	/**
	 * The item in question
	 */
	@Prop() item: any;

	/**
	 * The value of the column
	 */
	@Prop() value: any;

	/**
	 * Wether the table has actions
	 */
	@Prop() tableHasActions: boolean = false;

	/**
	 * The checkbox to show
	 */
	@Prop() checkbox: any;

	/**
	 * The template to show
	 */
	@Prop() template: TableDefinitionTemplateFunc = ({
		value,
	}: TableDefinitionData) => value;

	get data(): TableDefinitionData | { value: string } {
		if (this.variant === 'header') {
			return {
				value: this.value,
			};
		}

		return {
			value: this.value ?? objectGetByPath(this.item, this.definition.path),
			item: this.item,
			index: this.index,
			rowIndex: this.rowIndex,
		};
	}

	render() {
		return (
			<Host
				class={{
					'p-table-cell': true,
					[`variant-${this.variant}`]: true,
					...this._getColumnClasses(),
				}}
			>
				{this.checkbox}

				{this._getContent()}
			</Host>
		);
	}

	private _getContent() {
		if (this.variant === 'loading') {
			return (
				<p-loader
					variant='ghost'
					class='h-6 w-full flex-1 rounded'
				/>
			);
		}

		if (this.variant === 'actions') {
			return <slot name='actions'></slot>;
		}

		return (
			<div
				class={{
					flex: true,
					'justify-start': this.definition.align === 'start',
					'justify-center': this.definition.align === 'center',
					'justify-end': this.definition.align === 'end',
				}}
			>
				{this.variant === 'header' ? (
					this.data.value
				) : this.definition.useSlot ? (
					<slot />
				) : (
					this.template(this.data as TableDefinitionData)
				)}
			</div>
		);
	}

	private _getColumnClasses() {
		const sizes = this.definition ? this._getSizes(this.definition) : {};
		const isLastValues = this.definition
			? this._getIsLastValues(this.definition)
			: {};

		return {
			'justify-start':
				!this.definition?.align || this.definition?.align === 'start',
			'justify-center': this.definition?.align === 'center',
			'justify-end': this.definition?.align === 'end',
			'font-semibold':
				this.variant !== 'header' && this.definition?.type === 'th',
			'text-storm-dark':
				this.variant !== 'header' && this.definition?.type === 'th',
			'group-hover:flex': this.variant === 'actions' && this.tableHasActions,
			hidden: this.variant === 'actions' && this.tableHasActions,
			...sizes,
			...isLastValues,
		};
	}

	/*
     With this, we shall hack the system in ways no one would ever have thought.

     <div class="w-1/12 w-2/12 w-3/12 w-4/12 w-5/12 w-6/12 w-7/12 w-8/12 w-9/12 w-10/12 w-11/12 w-12/12"></div>
     <div class="tablet:w-1/12 tablet:w-2/12 tablet:w-3/12 tablet:w-4/12 tablet:w-5/12 tablet:w-6/12 tablet:w-7/12 tablet:w-8/12 tablet:w-9/12 tablet:w-10/12 tablet:w-11/12 tablet:w-12/12"></div>
     <div class="desktop-xs:w-1/12 desktop-xs:w-2/12 desktop-xs:w-3/12 desktop-xs:w-4/12 desktop-xs:w-5/12 desktop-xs:w-6/12 desktop-xs:w-7/12 desktop-xs:w-8/12 desktop-xs:w-9/12 desktop-xs:w-10/12 desktop-xs:w-11/12 desktop-xs:w-12/12"></div>
     <div class="desktop-xs:w-1/12 desktop-xs:w-2/12 desktop-xs:w-3/12 desktop-xs:w-4/12 desktop-xs:w-5/12 desktop-xs:w-6/12 desktop-xs:w-7/12 desktop-xs:w-8/12 desktop-xs:w-9/12 desktop-xs:w-10/12 desktop-xs:w-11/12 desktop-xs:w-12/12"></div>
     <div class="desktop-sm:w-1/12 desktop-sm:w-2/12 desktop-sm:w-3/12 desktop-sm:w-4/12 desktop-sm:w-5/12 desktop-sm:w-6/12 desktop-sm:w-7/12 desktop-sm:w-8/12 desktop-sm:w-9/12 desktop-sm:w-10/12 desktop-sm:w-11/12 desktop-sm:w-12/12"></div>
     <div class="desktop:w-1/12 desktop:w-2/12 desktop:w-3/12 desktop:w-4/12 desktop:w-5/12 desktop:w-6/12 desktop:w-7/12 desktop:w-8/12 desktop:w-9/12 desktop:w-10/12 desktop:w-11/12 desktop:w-12/12"></div>
     <div class="desktop-lg:w-1/12 desktop-lg:w-2/12 desktop-lg:w-3/12 desktop-lg:w-4/12 desktop-lg:w-5/12 desktop-lg:w-6/12 desktop-lg:w-7/12 desktop-lg:w-8/12 desktop-lg:w-9/12 desktop-lg:w-10/12 desktop-lg:w-11/12 desktop-lg:w-12/12"></div>
     <div class="desktop-xl:w-1/12 desktop-xl:w-2/12 desktop-xl:w-3/12 desktop-xl:w-4/12 desktop-xl:w-5/12 desktop-xl:w-6/12 desktop-xl:w-7/12 desktop-xl:w-8/12 desktop-xl:w-9/12 desktop-xl:w-10/12 desktop-xl:w-11/12 desktop-xl:w-12/12"></div>
     <div class="hidden flex group-hover:hidden group-hover:flex"></div>
     <div class="tablet:hidden tablet:flex tablet:group-hover:hidden tablet:group-hover:flex"></div>
     <div class="desktop-xs:hidden desktop-xs:flex desktop-xs:group-hover:hidden desktop-xs:group-hover:flex"></div>
     <div class="desktop-sm:hidden desktop-sm:flex  desktop-sm:group-hover:hidden desktop-sm:group-hover:flex"></div>
     <div class="desktop:hidden desktop:flex desktop:group-hover:hidden desktop:group-hover:flex"></div>
     <div class="desktop-lg:hidden desktop-lg:flex desktop-lg:group-hover:hidden desktop-lg:group-hover:flex"></div>
     <div class="desktop-xl:hidden desktop-xl:flex desktop-xl:group-hover:hidden desktop-xl:group-hover:flex"></div>


        ⠀⠀⠀⠀⠀⣠⣴⣶⣿⣿⠿⣷⣶⣤⣄⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣠⣴⣶⣷⠿⣿⣿⣶⣦⣀⠀⠀⠀⠀⠀
        ⠀⠀⠀⢀⣾⣿⣿⣿⣿⣿⣿⣿⣶⣦⣬⡉⠒⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠚⢉⣥⣴⣾⣿⣿⣿⣿⣿⣿⣿⣧⠀⠀⠀⠀
        ⠀⠀⠀⡾⠿⠛⠛⠛⠛⠿⢿⣿⣿⣿⣿⣿⣷⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣠⣾⣿⣿⣿⣿⣿⠿⠿⠛⠛⠛⠛⠿⢧⠀⠀⠀
        ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⠻⣿⣿⣿⣿⣿⡄⠀⠀⠀⠀⠀⠀⣠⣿⣿⣿⣿⡿⠟⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
        ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⢿⣿⡄⠀⠀⠀⠀⠀⠀⠀⠀⢰⣿⡿⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
        ⠀⠀⠀⠀⠀⠀⠀⣠⣤⠶⠶⠶⠰⠦⣤⣀⠀⠙⣷⠀⠀⠀⠀⠀⠀⠀⢠⡿⠋⢀⣀⣤⢴⠆⠲⠶⠶⣤⣄⠀⠀⠀⠀⠀⠀⠀
        ⠀⠘⣆⠀⠀⢠⣾⣫⣶⣾⣿⣿⣿⣿⣷⣯⣿⣦⠈⠃⡇⠀⠀⠀⠀⢸⠘⢁⣶⣿⣵⣾⣿⣿⣿⣿⣷⣦⣝⣷⡄⠀⠀⡰⠂⠀
        ⠀⠀⣨⣷⣶⣿⣧⣛⣛⠿⠿⣿⢿⣿⣿⣛⣿⡿⠀⠀⡇⠀⠀⠀⠀⢸⠀⠈⢿⣟⣛⠿⢿⡿⢿⢿⢿⣛⣫⣼⡿⣶⣾⣅⡀⠀
        ⢀⡼⠋⠁⠀⠀⠈⠉⠛⠛⠻⠟⠸⠛⠋⠉⠁⠀⠀⢸⡇⠀⠀⠄⠀⢸⡄⠀⠀⠈⠉⠙⠛⠃⠻⠛⠛⠛⠉⠁⠀⠀⠈⠙⢧⡀
        ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣿⡇⢠⠀⠀⠀⢸⣷⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
        ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣾⣿⡇⠀⠀⠀⠀⢸⣿⣷⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
        ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣰⠟⠁⣿⠇⠀⠀⠀⠀⢸⡇⠙⢿⣆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
        ⠀⠰⣄⠀⠀⠀⠀⠀⠀⠀⠀⢀⣠⣾⠖⡾⠁⠀⠀⣿⠀⠀⠀⠀⠀⠘⣿⠀⠀⠙⡇⢸⣷⣄⡀⠀⠀⠀⠀⠀⠀⠀⠀⣰⠄⠀
        ⠀⠀⢻⣷⡦⣤⣤⣤⡴⠶⠿⠛⠉⠁⠀⢳⠀⢠⡀⢿⣀⠀⠀⠀⠀⣠⡟⢀⣀⢠⠇⠀⠈⠙⠛⠷⠶⢦⣤⣤⣤⢴⣾⡏⠀⠀
        ⠀⠀⠈⣿⣧⠙⣿⣷⣄⠀⠀⠀⠀⠀⠀⠀⠀⠘⠛⢊⣙⠛⠒⠒⢛⣋⡚⠛⠉⠀⠀⠀⠀⠀⠀⠀⠀⣠⣿⡿⠁⣾⡿⠀⠀⠀
        ⠀⠀⠀⠘⣿⣇⠈⢿⣿⣦⠀⠀⠀⠀⠀⠀⠀⠀⣰⣿⣿⣿⡿⢿⣿⣿⣿⣆⠀⠀⠀⠀⠀⠀⠀⢀⣼⣿⡟⠁⣼⡿⠁⠀⠀⠀
        ⠀⠀⠀⠀⠘⣿⣦⠀⠻⣿⣷⣦⣤⣤⣶⣶⣶⣿⣿⣿⣿⠏⠀⠀⠻⣿⣿⣿⣿⣶⣶⣶⣦⣤⣴⣿⣿⠏⢀⣼⡿⠁⠀⠀⠀⠀
        ⠀⠀⠀⠀⠀⠘⢿⣷⣄⠙⠻⠿⠿⠿⠿⠿⢿⣿⣿⣿⣁⣀⣀⣀⣀⣙⣿⣿⣿⠿⠿⠿⠿⠿⠿⠟⠁⣠⣿⡿⠁⠀⠀⠀⠀⠀
        ⠀⠀⠀⠀⠀⠀⠈⠻⣯⠙⢦⣀⠀⠀⠀⠀⠀⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠉⠀⠀⠀⠀⠀⣠⠴⢋⣾⠟⠀⠀⠀⠀⠀⠀⠀
        ⠀⠀⠀⠀⠀⠀⠀⠀⠙⢧⡀⠈⠉⠒⠀⠀⠀⠀⠀⠀⣀⠀⠀⠀⠀⢀⠀⠀⠀⠀⠀⠐⠒⠉⠁⢀⡾⠃⠀⠀⠀⠀⠀⠀⠀⠀
        ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠳⣄⠀⠀⠀⠀⠀⠀⠀⠀⠻⣿⣿⣿⣿⠋⠀⠀⠀⠀⠀⠀⠀⠀⣠⠟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
        ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⢦⡀⠀⠀⠀⠀⠀⠀⠀⣸⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⢀⡴⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
        ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
        ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠐⣿⣿⣿⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
        ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⣿⣿⡿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
        ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢻⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
        ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠸⣿⣿⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
    */
	private _getSizes({ sizes }: TableColumn) {
		if (sizes === 'auto' || !sizes) {
			return {
				'w-auto': true,
			};
		}

		if (sizes === 'hidden') {
			return {
				hidden: true,
			};
		}

		if (typeof sizes === 'object') {
			sizes = sizes as TableColumnSizes;
			const classes: any = {};
			let previousSize: TableColumnSizesKey | undefined;

			for (let size in sizes) {
				if (!isTableColumnSizesKey(sizes, size)) {
					continue;
				}

				if (size === 'default') {
					if (sizes.default === 'hidden') {
						classes['hidden'] = true;
						previousSize = size;
						continue;
					}

					classes[`w-${sizes.default}/12`] = true;
					previousSize = size;
					continue;
				}

				const currentValue = sizes[size];
				const previousValue = previousSize ? sizes[previousSize] : null;
				if (
					currentValue !== 'hidden' &&
					previousValue &&
					previousValue === 'hidden'
				) {
					classes[`${size}:flex`] = true;
				}

				if (currentValue === 'hidden') {
					classes[`${size}:hidden`] = true;
					previousSize = size;
					continue;
				}

				if (currentValue === 12 || currentValue === 'full') {
					classes[`${size}:w-full`] = true;
				}

				classes[`${size}:w-${currentValue}/12`] = true;
				previousSize = size;
			}

			return classes;
		}

		if (sizes === 12 || sizes === 'full') {
			return {
				'w-full': true,
			};
		}

		// is a number.
		return {
			[`w-${sizes}/12`]: true,
		};
	}

	private _getIsLastValues(
		{
			isLast,
			parsedSizes,
		}: {
			isLast: { [key: string]: boolean };
			parsedSizes: TableColumnSizes;
		} /* Table Definition */
	) {
		const values: { [key: string]: boolean } = {};

		for (let size of Object.keys(isLast)) {
			let prefix = '';
			if (size !== 'default') {
				prefix = `${size}:`;
			}

			values[`${prefix}pr-4`] = !isLast[size];

			values[`${prefix}group-hover:hidden`] =
				isLast[size] && this.tableHasActions && this.variant !== 'actions';

			values[`${prefix}group-hover:flex`] =
				parsedSizes[size as keyof TableColumnSizes] !== 'hidden' ||
				this.variant === 'actions';

			values[`${prefix}flex`] =
				parsedSizes[size as keyof TableColumnSizes] !== 'hidden' &&
				this.variant !== 'actions';
		}

		return values;
	}
}
